### ISSUE TITLE
event["extra"] is deprecated

### ISSUE THREAD

**Issue by Lacrymology** [kiwicom/structlog-sentry#50]
We've forked and integrated structlog-sentry in our software, but the "additional data" field in sentry is deprecated, and in our instances only 10 keys show up.

We've updated the code to use a local scope's context instead (https://docs.sentry.io/platforms/python/enriching-events/scopes/#local-scopes), and we'd like to know whether you want a PR with that, and whether keeping the code that adds to `event["extra"]` is important for some reason. We've first added `as_extra: bool, as_context: bool` but that's weird because they should be exclusive. We're talking about changing it to `send_as: Optional[Enum("context", "extra")]`, but that completely breaks the interface.

Tell us your preference and we can do that, or if it doesn't work for us, I'll backport our additions to keep backwards compatibility as necessary

**Comment by paveldedik** [comment]
Hi, I removed extra (and replaced it with context) in new `2.0.0b1` version. You can check the full list of changes here - https://github.com/kiwicom/structlog-sentry/pull/79 I still need to test the changes properly, that's why it is a beta right now.

But I think we can close this issue for now (If you think we should keep it open, feel free to reopen or create a new issue).
